### ISSUE TITLE
[BUG] - Troubleshooting fail2ban docker container.

### ISSUE THREAD

**Issue by ektorasdj** [telnetdoogie/synology-docker#30]
I will describe below how to set up the Fail2ban container from CrazyMax in a simple manner, as well as the steps to reproduce the issue of the container not adding iptable rules after the Docker update to version 28 and new custom iptable modules:

First, here is a simple compose file for testing, with certain privileges to provide direct access to the host’s iptable system.

```
version: '3'
services:
  fail2ban:
    container_name: fail2ban
    restart: always
    image: crazymax/fail2ban:latest
    environment: 
      - TZ=Etc/UTC
      - F2B_DB_PURGE_AGE=7d
      - F2B_LOG_TARGET=STDOUT
      - IPTABLES_MODE=legacy
      - F2B_LOG_LEVEL=INFO
    volumes:
      - /path/to/data/:/data  # We need this to make some changes for Synology, so please use a folder that exists
      - /var/log:/var/log:ro
      - /path/to/emptylog.log:/emptylog.log #we also need an empty log file for the jail to work
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
```

After the container is up, you should go into the data directory you have added on the host. Following the guide here: https://github.com/sosandroid/docker-fail2ban-synology and since REJECT rules don't work, we need to change the action to DROP.

First, in the /path/to/data/ directory you used, after the container is up, you should have the following folder structure:

    action.d
    db
    filter.d
    jail.d

This can be done by creating a file called iptables.local inside the action.d directory with this content:
```
[Init]
blocktype = DROP
[Init?family=inet6]
blocktype = DROP
```
Next, we will create a dummy jail and filter files so we can force-ban an IP from the command line. Inside the jail.d folder, create a file called vaultwarden.conf with this content:
```
[DEFAULT]
bantime = 2592000
findtime = 86400
maxretry = 5
ignoreip = 192.168.0.0/24  # It's best to add your local network here to avoid locking yourself out in case it works.Be sure to remove this comment to avoid issues with the config.
banaction = iptables-allports
ignoreself = false

[vaultwarden]
enabled = true
port = 5151,80,443,6690  # Doesn't matter since above, the banaction should block all ports.Be sure to remove this comment to avoid issues with the config.
filter = vaultwarden
logpath = /emptylog.log
```
Now, in the filter.d folder, create a file called vaultwarden.conf with this content:
```
[INCLUDES]
before = common.conf

[Definition]
failregex = ^.*Username or password is incorrect\. Try again\. IP: <ADDR>\. Username:.*$
ignoreregex =
```
Now, restart the container, and in the container logs, you should see:
```
[1]: INFO    Jail 'vaultwarden' started
```
Since the log file does not exist, nothing will be banned automatically. However, you can use this command to test if it works (Here, add the public IP you want to test the ban with—of course, not the same as the network your NAS is currently on. I used the public IP of my mobile when it was connected through mobile data and tried to connect from my mobile to my internet-facing services).
```
docker exec -t fail2ban fail2ban-client set vaultwarden banip 87.249.133.236
#In case you want to Unban an IP , its the same command as above but instead of "banip" you use "unbanip".
```
Now the logs should show:
```
[1]: NOTICE  [vaultwarden] Ban 87.249.133.236
```

To test, try to connect from this public IP to any of your internet services for Synology or list the rules from SSH on your Synology using root:
```
iptables -L -v -n --line-numbers
```
If it worked, you should not be able to connect, and a new chain should be created in iptables with the name vaultwarden.
