### ISSUE TITLE
[BUG] Sometimes after update, containers on the same network cannot reach each other

### ISSUE THREAD

**Issue by telnetdoogie** [telnetdoogie/synology-docker#9]
**Describe the bug**
if the `start_stop_status` script isn't successfully updated during the update, containers will fail to be able to reach each other due to a missing ipchains rule.

**To reproduce**
create two test containers:
```yml
services:
  test_alpine2:
    container_name: test_alpine2
    image: alpine:latest
    command: tail -F anything

  test_alpine:
    container_name: test_alpine
    image: alpine:latest
    command: tail -F anything
```
run the containers with `docker-compose up -d`
enter the console of `test_alpine`:
`docker-compose exec test_alpine /bin/sh -i`
attempt to ping container2 from container1:
`ping test_alpine`
the pings will timeout.

**Expected behavior**
after performing the above test, the pings should succeed.

**Additional context**
looking in the `/var/packages/ContainerManager/scripts/start-stop-status` there will be no entry `iptables -P FORWARD ACCEPT`.

**As a short term fix / validation that "yes this was indeed my issue" you can issue the command
`sudo iptables -P FORWARD ACCEPT` and the intra-container connectivity should immediately resolve.**
